 export enum AddToCartActionType {
    CLEAR_ALL_DATA_CART= 'CLEAR_ALL_DATA_CART',
    PRODUCT_TO_CART = 'PRODUCT_TO_CART',
    ORDER_TO_CART = 'ORDER_TO_CART',
    UPDATE_PRODUCT_TO_CART = 'UPDATE_PRODUCT_TO_CART',
    REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
}
