 export enum ShippingsActionType {

    ADD_IMAGE_PRODUCT = 'ADD_IMAGE_PRODUCT',
    HAS_MORE_DATA_STREAM = 'HAS_MORE_DATA_STREAM',
    NOT_MORE_DATA_STREAM = 'NOT_MORE_DATA_STREAM',
    REQUEST_PAGE_STREAM = 'REQUEST_PAGE_STREAM',
    LAST_PRODUCT_STREAM = 'LAST_PRODUCT_STREAM',
    HAS_MORE_DATA_PROFILE = 'HAS_MORE_DATA_PROFILE',
    NOT_MORE_DATA_PROFILE = 'NOT_MORE_DATA_PROFILE',
    REQUEST_PAGE_PROFILE = 'REQUEST_PAGE_PROFILE',
    LAST_PRODUCT_PROFILE = 'LAST_PRODUCT_PROFILE',
    ADD_VIDEO_PRODUCT = 'ADD_VIDEO_PRODUCT',
    ADD_PRODUCT = 'ADD_PRODUCT',
    UPDATE_PRODUCT = 'UPDATE_PRODUCT',
    UPDATE_PRODUCT_COMMENTS = 'UPDATE_PRODUCT_COMMENTS',
    UPDATE_PRODUCT_VOTES = 'UPDATE_PRODUCT_VOTES',
    DELETE_PRODUCT = 'DELETE_PRODUCT',
    ADD_LIST_SHIPPING_RIGIONS = 'ADD_LIST_SHIPPING_RIGIONS',
    ADD_LIST_SHIPPING_RATES = 'ADD_LIST_SHIPPING_RATES',
    CLEAR_ALL_DATA_PRODUCT = 'CLEAR_ALL_DATA_PRODUCT',
    ADD_SHIPPING_ADDRESS = 'ADD_SHIPPING_ADDRESS'
}
